# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_auto_20170417_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
