# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='user',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
