# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_auto_20170703_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submit_method',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
