# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_ticket_submit_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'results'},
        ),
    ]
