# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0012_auto_20171118_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': (('view_answers', 'Can view answers'),)},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'permissions': (('view_own_results', 'Can view own results'), ('view_all_results', 'Can view all results'), ('disqualify_results', 'Can disqualify results from a drawing')), 'verbose_name_plural': 'results'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('view_own_tickets', 'Can view own tickets'), ('view_all_tickets', 'Can view all tickets'))},
        ),
    ]
