# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0013_auto_20171118_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
