# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-22 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0014_auto_20181121_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scratchoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date submitted')),
                ('submit_method', models.CharField(max_length=200)),
                ('number_chosen', models.PositiveIntegerField()),
                ('answer', models.PositiveIntegerField()),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_own_scratchoff', 'Can view own scratchoff'), ('view_all_scratchoffs', 'Can view all scratchoffs')),
            },
        ),
    ]
