# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-11-06 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0016_auto_20181122_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchoff',
            name='points_awarded',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scratchoff',
            name='points_possible',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
