# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-11-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0017_auto_20221105_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchoff',
            name='answer',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
