# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-11-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0018_auto_20221106_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchoff',
            name='points_awarded',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='scratchoff',
            name='points_possible',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
