# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-11-23 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0019_auto_20221123_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchoff',
            name='points_awarded',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scratchoff',
            name='points_possible',
            field=models.FloatField(),
        ),
    ]
