# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-11-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0020_auto_20221123_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='scratchoff_number_correct',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='scratchoff_number_possible',
            field=models.FloatField(default=1),
        ),
    ]
