# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2024-11-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0021_auto_20221123_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='ranking_system',
            field=models.CharField(choices=[('weighted_avg', 'Weighted average'), ('ranking_points', 'Ranking points ("Mario Kart scoring")')], default='weighted_avg', max_length=200),
        ),
    ]
